window.___jsl=window.___jsl||{};
window.___jsl.h=window.___jsl.h||'r;gc\/25095437-ce843676';
window.___jsl.l=[];
window.___gpq=[];
window.gapi=window.gapi||{};
window.gapi.plusone=window.gapi.plusone||(function(){
  function f(n){return function(){window.___gpq.push(n,arguments)}}
  return{go:f('go'),render:f('render')}})();
function __bsld(){var p=window.gapi.plusone=window.googleapisv0.plusone;var f;while(f=window.___gpq.shift()){
  p[f]&&p[f].apply(p,window.___gpq.shift())}
p=window.gapi.plus=window.googleapisv0.plus;while(f=window.___gbq.shift()){
  p[f]&&p[f].apply(p,window.___gbq.shift())}
if (gadgets.config.get("gwidget")["parsetags"]!=="explicit"){gapi.plusone.go();}}
window.___gbq=[];
window.gapi.plus=window.gapi.plus||(function(){
  function f(n){return function(){window.___gbq.push(n,arguments)}}
  return{go:f('go'),render:f('render')}})();
window.__GOOGLEAPIS=window.__GOOGLEAPIS||{};
window.__GOOGLEAPIS.iframes=window.__GOOGLEAPIS.iframes||{};
window.__GOOGLEAPIS.iframes.plus=window.__GOOGLEAPIS.iframes.plus||{url:':socialhost:/u/:session_index:/_/pages/badge'};window['___jsl'] = window['___jsl'] || {};window['___jsl']['u'] = 'https:\/\/apis.google.com\/js\/plusone.js';window['___jsl']['f'] = ['googleapis.client','plusone','gcm_ppb'];window['___jsl']['ms'] = 'https://plus.google.com';(window['___jsl']['ci'] = (window['___jsl']['ci'] || [])).push({"gwidget":{"parsetags":"onload","superbatch":false},"iframes":{"sharebox":{"params":{"json":"&"},"url":":socialhost:/:session_prefix:_/sharebox/dialog"},"plus":{"url":":socialhost:/:session_prefix:_/pages/badge"},":socialhost:":"https://plusone.google.com","plusone_m":{"url":":socialhost:/:session_prefix:_/+1/fastbutton","params":{"count":"","size":"","url":""}},"card":{"params":{"style":"#","userid":"&"},"url":":socialhost:/u/:session_index:/_/hovercard/card"},"plusone":{"url":":socialhost:/:session_prefix:_/+1/fastbutton","params":{"count":"","size":"","url":""}}},"googleapis.config":{"requestCache":{"enabled":true},"methods":{"chili.people.list":true,"pos.plusones.list":true,"pos.plusones.get":true,"chili.people.get":true,"pos.plusones.insert":true,"chili.activities.list":true,"pos.plusones.delete":true,"chili.activities.get":true,"chili.activities.search":true,"pos.plusones.getSignupState":true},"versions":{"chili":"v1","pos":"v1"},"rpc":"/rpc","transport":{"isProxyShared":true},"sessionCache":{"enabled":true},"root-1p":"https://clients6.google.com","root":"https://www.googleapis.com","xd3":"/static/proxy.html","developerKey":"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ","auth":{"useInterimAuth":false}}});var gapi=window.gapi||{};gapi.client=window.gapi&&window.gapi.client||{};
(function(){var p=void 0,q=void 0,r="___jsl",I="h",m="l",J="m",s="ms",K="ci",t="cu",L="c",M="cm",N="o",n="p",i="q",k="https://ssl.gstatic.com",O="/webclient/js",o="config_1p",P="/webclient/jsx/",u="https://apis.google.com",v=".js",Q="gcjs-3p",R=/^(https?:)?\/\/([^/:@]*)(:[0-9]+)?(\/[\w.,:!=/-]*)(\?[^#]*)?(#.*)?$/,w=/^[?#]([^&]*&)*jsh=([^&]*)/,x="d",j="r",S="f",l="m",y="n",T="sync",U="callback",z="config",A="nodep",B="gapi.load: ",C=function(a,b){p&&p(a,b);throw B+a+(b&&" "+b);},D=function(a){q&&q(a);
var b=window.console;b&&b.warn(B+a)},V=function(a,b,e){a=a[I];if(b=b&&w.exec(b)||e&&w.exec(e))try{a=decodeURIComponent(b[2])}catch(f){D("Invalid hint "+b[2])}return a},E=function(a){a.sort();for(var b=0;b<a.length;)!a[b]||b&&a[b]==a[b-1]?a.splice(b,1):++b},W=function(a,b){for(var e=true,f=0,c=0,d,g;e&&(d=a[f])&&(g=b[c]);)d==g?++f:d<g&&(e=false),++c;return e&&!d},X=function(a){if(document.readyState!="loading")return false;if(typeof window.___gapisync!="undefined")return window.___gapisync;if(a&&(a=
a[T],typeof a!="undefined"))return a;for(var a=document.getElementsByTagName("meta"),b=0,e;e=a[b];++b)if("generator"==e.getAttribute("name")&&"blogger"==e.getAttribute("content"))return true;return false},Y=function(a){var b=document.createElement("script");b.setAttribute("src",a);a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)},Z=function(a,b,e,f,c){var d=e.shift(),g;g=d==j?k:d==l?f[s]||u:(g=e.shift())&&g.replace(/\/+$/,"");var h;d==j?(h=e.shift(),h=(h.indexOf(P)?O+"/":
"")+h):h=e.shift();var F=d==x,i=F&&e.shift()||Q,e=F&&e.shift();if(d==x)c=h,h=i,a="/"+a.join(":")+(b.length?"!"+b.join(":"):"")+v+"?container="+h+"&c=2&jsload=0",c&&(a+="&r="+c),e=="d"&&(a+="&debug=1");else if(d==j||d==S)c=h,a=(c.indexOf("/")?"/":"")+c+"/"+a.join("__")+(b.length?"--"+b.join("__"):"")+v;else if(d==l||d==y)b=h,a=a.join(",").replace(/\./g,"_").replace(/-/g,"_"),a=b.replace("__features__",a),a=c[A]?a.replace("/d=1/","/d=0/"):a;else return D("Unknown hint type "+d),"";if(!g)return"";g+=
a;a=g;b=f;if(c=f=R.exec(a))if(c=!/\.\.|\/\//.test(f[4]))b:if(c=a,f=f[2],d==j)c=c.substr(0,k.length)==k;else if(d==l)f=b[s]||u,c=c.substr(0,f.length)==f;else{d=b[J];if(f&&d){d=d.split(",");b=0;for(c=d.length;b<c;++b)if(e=d[b],h=f.lastIndexOf(e),(h==0||e.charAt(0)=="."||f.charAt(h-1)==".")&&f.length-e.length==h){c=true;break b}}c=false}c||C("Invalid URI",a);return g},$=function(a,b,e){(a[i]=a[i]||[]).push([b,e])},H=function(a){a[i]&&a[i].length>0&&(window.gapi.load||G).apply(null,a[i].shift())},aa=
function(a){for(var b=1;b<a.length;++b)if(a[b]==o){a.splice(b,1);a.unshift(o);break}},G=function(a,b){var e,f={};typeof b!=="function"?(f=b||{},e=f[U]):e=b;var c=window[r]=window[r]||{};if(c[n])$(c,a,b);else{var d=V(c,window.location.search,window.location.hash);d||C("No hint present","");var g=d.split(";"),h=g[0]==l||g[0]==y,d=a.split(":");h&&!c[K]&&d.push(o);f[A]||E(d);var i=c[m]=c[m]||[];E(i);var j=function(a){if(a)try{a()}catch(b){return b}return null};if(!W(d,i)){aa(d);var k=h?M:L,g=Z(d,i,g,
c,f);f[z]&&(c[t]=c[t]||[]).push(f[z]);if(g){c[n]=d;c[N]=1;c[k]=function(){delete c[n];delete c[k];var a=j(e);H(c);if(a)throw a;};[].push.apply(c[m],d);X(f)?document.write('<script src="'+encodeURI(g)+'"><\/script>'):Y(g);return}}f=j(e);H(c);if(f)throw f;}};gapi.loader={load:G}})();
gapi.load=window.___jsl&&window.___jsl.il&&window.gapi&&window.gapi.load||gapi.loader.load;
(window.gapi=window.gapi||{}).load=window.___jsl&&window.___jsl.il&&window.gapi.load||gapi.load;
gapi.load('googleapis.client:plusone:gcm_ppb', {'callback': window['__bsld']  });